### ISSUE TITLE
can't scan qr

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/moontree#503]
### Describe The Bug

camra never comes up

### To Reproduce

use iphone

### Expected Behavior

same as android

**Comment by lastmeta** [comment]
might be permission issue

**Comment by lastmeta** [comment]
solved by the permissions set correctly for ios

**Comment by Whale-Street** [comment]
This still exists and is actually not iOS centric. 
![Screenshot_20220504-101736_Squid](https://user-images.githubusercontent.com/9276931/166732462-9850ddb4-6566-457c-9e6a-38a0095fbc1b.jpg)

**Comment by lastmeta** [comment]
fixed above comment, but we should probably try to ask for permissions again or something too.
